# Generated by Django 2.1.3 on 2018-11-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=256)),
                ('score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('emotion', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
