# Generated by Django 2.1.3 on 2018-11-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=256)),
                ('trigger_content', models.CharField(max_length=256)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
