# Generated by Django 2.1.3 on 2018-11-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_warning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='CWDocument',
        ),
    ]
