# Generated by Django 2.1.3 on 2018-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_warning', '0002_auto_20181116_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwdocument',
            name='probability',
        ),
        migrations.AddField(
            model_name='cwdocument',
            name='unsafe',
            field=models.BooleanField(default=False),
        ),
    ]
